name: Test
on:
  push:

permissions:
  contents: read
  id-token: write
  pull-requests: write
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/987979088361/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: gh-action@naturalselectionlabs.iam.gserviceaccount.com
          create_credentials_file: true

      - name: Test
        run: cargo test --lib
